## 1... Importing dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('indices_macro_weekly_cleaned.csv')
raw_data.head()

,Unnamed: 0,Close_^DJI,Close_^FCHI,Close_^FTSE,Close_^GDAXI,Close_^GSPTSE,Close_^HSI,Close_^IXIC,Close_^N225,Volume_^DJI,...,WBAA,DPSACBW027SBOG,WCOILWTICO,WGS30YR,WRESBAL,WGS20YR,MORTGAGE15US,WPRIME,CCSA,TOTCI
0,1992-01-06,3200.100098,1787.599976,2493.199951,1604.689941,3524.800049,4307.000000,597.900024,23801.179688,27280000.0,...,9.11,2452.0455,19.11,7.45,27.582,7.36,7.79,6.5,3410000.0,615.0323
1,1992-01-13,3185.600098,1824.300049,2490.100098,1620.449951,3594.399902,4325.899902,617.630005,21696.859375,19300000.0,...,9.05,2466.9217,18.41,7.43,27.535,7.36,7.79,6.5,3342000.0,614.2388
2,1992-01-20,3254.000000,1865.900024,2544.899902,1685.140015,3655.699951,4510.500000,619.380005,20913.820312,18190000.0,...,9.11,2482.4544,18.81,7.57,25.833,7.36,8.03,6.5,3297000.0,614.7461
3,1992-01-27,3240.600098,1869.300049,2539.899902,1686.709961,3628.500000,4554.700195,621.000000,21007.109375,19110000.0,...,9.16,2485.0001,18.66,7.65,26.471,7.36,8.14,6.5,3364000.0,612.9025
4,1992-02-03,3234.100098,1857.000000,2560.199951,1685.660034,3594.399902,4672.100098,623.429993,22139.589844,18860000.0,...,9.20,2479.4654,19.05,7.74,21.911,7.36,8.28,6.5,3301000.0,612.8218

In [3]:
# Set 'date' as the index
raw_data['date'] = pd.to_datetime(raw_data['Unnamed: 0'])
raw_data.set_index('date', inplace=True)
raw_data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
raw_data.head()

,Close_^DJI,Close_^FCHI,Close_^FTSE,Close_^GDAXI,Close_^GSPTSE,Close_^HSI,Close_^IXIC,Close_^N225,Volume_^DJI,Volume_^FCHI,...,WBAA,DPSACBW027SBOG,WCOILWTICO,WGS30YR,WRESBAL,WGS20YR,MORTGAGE15US,WPRIME,CCSA,TOTCI
date,,,,,,,,,,,,,,,,,,,,,
1992-01-06,3200.100098,1787.599976,2493.199951,1604.689941,3524.800049,4307.000000,597.900024,23801.179688,27280000.0,0.0,...,9.11,2452.0455,19.11,7.45,27.582,7.36,7.79,6.5,3410000.0,615.0323
1992-01-13,3185.600098,1824.300049,2490.100098,1620.449951,3594.399902,4325.899902,617.630005,21696.859375,19300000.0,0.0,...,9.05,2466.9217,18.41,7.43,27.535,7.36,7.79,6.5,3342000.0,614.2388
1992-01-20,3254.000000,1865.900024,2544.899902,1685.140015,3655.699951,4510.500000,619.380005,20913.820312,18190000.0,0.0,...,9.11,2482.4544,18.81,7.57,25.833,7.36,8.03,6.5,3297000.0,614.7461
1992-01-27,3240.600098,1869.300049,2539.899902,1686.709961,3628.500000,4554.700195,621.000000,21007.109375,19110000.0,0.0,...,9.16,2485.0001,18.66,7.65,26.471,7.36,8.14,6.5,3364000.0,612.9025
1992-02-03,3234.100098,1857.000000,2560.199951,1685.660034,3594.399902,4672.100098,623.429993,22139.589844,18860000.0,0.0,...,9.20,2479.4654,19.05,7.74,21.911,7.36,8.28,6.5,3301000.0,612.8218

In [5]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1716 entries, 1992-01-06 to 2024-11-18
Data columns (total 41 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Close_^DJI      1716 non-null   float64
 1   Close_^FCHI     1716 non-null   float64
 2   Close_^FTSE     1716 non-null   float64
 3   Close_^GDAXI    1716 non-null   float64
 4   Close_^GSPTSE   1716 non-null   float64
 5   Close_^HSI      1716 non-null   float64
 6   Close_^IXIC     1716 non-null   float64
 7   Close_^N225     1716 non-null   float64
 8   Volume_^DJI     1716 non-null   float64
 9   Volume_^FCHI    1716 non-null   float64
 10  Volume_^FTSE    1716 non-null   float64
 11  Volume_^GDAXI   1716 non-null   float64
 12  Volume_^GSPTSE  1716 non-null   float64
 13  Volume_^HSI     1716 non-null   float64
 14  Volume_^IXIC    1716 non-null   float64
 15  Volume_^N225    1716 non-null   float64
 16  SP500_Open      1716 non-null   float64
 17  SP500_Close     1716 non-null   float64
 18  SP500_Volume    1716 non-null   float64
 19  SP500_Wk_Vol    1716 non-null   float64
 20  MORTGAGE30US    1716 non-null   float64
 21  FF              1716 non-null   float64
 22  WGS10YR         1716 non-null   float64
 23  WAAA            1716 non-null   float64
 24  WTB3MS          1716 non-null   float64
 25  ICSA            1716 non-null   float64
 26  WGS1YR          1716 non-null   float64
 27  WGS2YR          1716 non-null   float64
 28  NFCI            1716 non-null   float64
 29  WTREGEN         1716 non-null   float64
 30  WGS5YR          1716 non-null   float64
 31  WBAA            1716 non-null   float64
 32  DPSACBW027SBOG  1716 non-null   float64
 33  WCOILWTICO      1716 non-null   float64
 34  WGS30YR         1716 non-null   float64
 35  WRESBAL         1716 non-null   float64
 36  WGS20YR         1716 non-null   float64
 37  MORTGAGE15US    1716 non-null   float64
 38  WPRIME          1716 non-null   float64
 39  CCSA            1716 non-null   float64
 40  TOTCI           1716 non-null   float64
dtypes: float64(41)
memory usage: 563.1 KB

## 2... Creating target variables

In [6]:
target_df = raw_data.copy()

In [7]:
target_df['RoR_Perc'] = 100*(target_df['SP500_Close']-target_df['SP500_Open'])/target_df['SP500_Open']

In [8]:
target_df['RoR_Perc'].describe()

count    1716.000000
mean        0.029003
std         1.097208
min        -8.489989
25%        -0.361399
50%         0.059237
75%         0.519825
max         9.926045
Name: RoR_Perc, dtype: float64

In [9]:
#target_df['RoR_Intensity'] = pd.qcut(target_df['RoR_Perc'], q=3, labels=[0, 1, 2])

In [10]:
#_, bins = pd.qcut(target_df['RoR_Perc'], q=3, labels=[0, 1, 2], retbins=True)
#print("Cutoff values:", bins)

In [11]:
# Calculate the 5th and 95th percentiles
low_cutoff = target_df['RoR_Perc'].quantile(0.05)
high_cutoff = target_df['RoR_Perc'].quantile(0.95)

# Apply the custom cutoff values using pd.cut
target_df['RoR_Intensity'] = pd.cut(
    target_df['RoR_Perc'],
    bins=[-float('inf'), low_cutoff, high_cutoff, float('inf')],
    labels=[0, 1, 2],
    include_lowest=True
)

# Print the cutoff values
print("Cutoff values: Low =", low_cutoff, ", High =", high_cutoff)

Cutoff values: Low = -1.7004729879952327 , High = 1.4739340398785834

In [12]:
target_df['RoR_Perc'].describe()

count    1716.000000
mean        0.029003
std         1.097208
min        -8.489989
25%        -0.361399
50%         0.059237
75%         0.519825
max         9.926045
Name: RoR_Perc, dtype: float64

In [13]:
target_df[['RoR_Perc', 'RoR_Intensity']].head()

            RoR_Perc RoR_Intensity
date
1992-01-06 -0.321959             1
1992-01-13 -0.171062             1
1992-01-20 -0.596858             1
1992-01-27 -0.108322             1
1992-02-03  0.181020             1

In [14]:
target_df['RoR_Intensity'].value_counts()

RoR_Intensity
1    1544
0      86
2      86
Name: count, dtype: int64

In [15]:
# Creating target variable as a rolling sum of the last 4 weeks

target_df['Rolling_RoR'] = target_df['RoR_Perc'].rolling(window=4).sum()

# Define the condition: if 'RoR_Percentage' is non-negative
condition = target_df['Rolling_RoR'] >= target_df['Rolling_RoR'].mean() + target_df['Rolling_RoR'].std()

# Create a column that marks upward trends (1 for True, 0 for False)
target_df['Target_Rolling'] = condition.astype(int)

target_df['Target_Rolling_shifted'] = target_df['Target_Rolling'].shift(-4)

target_df.head()

,Close_^DJI,Close_^FCHI,Close_^FTSE,Close_^GDAXI,Close_^GSPTSE,Close_^HSI,Close_^IXIC,Close_^N225,Volume_^DJI,Volume_^FCHI,...,WGS20YR,MORTGAGE15US,WPRIME,CCSA,TOTCI,RoR_Perc,RoR_Intensity,Rolling_RoR,Target_Rolling,Target_Rolling_shifted
date,,,,,,,,,,,,,,,,,,,,,
1992-01-06,3200.100098,1787.599976,2493.199951,1604.689941,3524.800049,4307.000000,597.900024,23801.179688,27280000.0,0.0,...,7.36,7.79,6.5,3410000.0,615.0323,-0.321959,1,NaN,0,0.0
1992-01-13,3185.600098,1824.300049,2490.100098,1620.449951,3594.399902,4325.899902,617.630005,21696.859375,19300000.0,0.0,...,7.36,7.79,6.5,3342000.0,614.2388,-0.171062,1,NaN,0,0.0
1992-01-20,3254.000000,1865.900024,2544.899902,1685.140015,3655.699951,4510.500000,619.380005,20913.820312,18190000.0,0.0,...,7.36,8.03,6.5,3297000.0,614.7461,-0.596858,1,NaN,0,0.0
1992-01-27,3240.600098,1869.300049,2539.899902,1686.709961,3628.500000,4554.700195,621.000000,21007.109375,19110000.0,0.0,...,7.36,8.14,6.5,3364000.0,612.9025,-0.108322,1,-1.198201,0,0.0
1992-02-03,3234.100098,1857.000000,2560.199951,1685.660034,3594.399902,4672.100098,623.429993,22139.589844,18860000.0,0.0,...,7.36,8.28,6.5,3301000.0,612.8218,0.181020,1,-0.695222,0,0.0

In [16]:
threshold = target_df['Rolling_RoR'].mean() + target_df['Rolling_RoR'].std()
threshold

2.074934836162436

In [17]:
target_df['Target_Rolling_shifted'].value_counts()

Target_Rolling_shifted
0.0    1515
1.0     197
Name: count, dtype: int64

In [18]:
target_df.drop(['Rolling_RoR', 'Target_Rolling'], axis=1, inplace=True)

# 3... Changing variables to Percentage Change

In [19]:
target_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1716 entries, 1992-01-06 to 2024-11-18
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Close_^DJI              1716 non-null   float64
 1   Close_^FCHI             1716 non-null   float64
 2   Close_^FTSE             1716 non-null   float64
 3   Close_^GDAXI            1716 non-null   float64
 4   Close_^GSPTSE           1716 non-null   float64
 5   Close_^HSI              1716 non-null   float64
 6   Close_^IXIC             1716 non-null   float64
 7   Close_^N225             1716 non-null   float64
 8   Volume_^DJI             1716 non-null   float64
 9   Volume_^FCHI            1716 non-null   float64
 10  Volume_^FTSE            1716 non-null   float64
 11  Volume_^GDAXI           1716 non-null   float64
 12  Volume_^GSPTSE          1716 non-null   float64
 13  Volume_^HSI             1716 non-null   float64
 14  Volume_^IXIC            1716 non-null   float64
 15  Volume_^N225            1716 non-null   float64
 16  SP500_Open              1716 non-null   float64
 17  SP500_Close             1716 non-null   float64
 18  SP500_Volume            1716 non-null   float64
 19  SP500_Wk_Vol            1716 non-null   float64
 20  MORTGAGE30US            1716 non-null   float64
 21  FF                      1716 non-null   float64
 22  WGS10YR                 1716 non-null   float64
 23  WAAA                    1716 non-null   float64
 24  WTB3MS                  1716 non-null   float64
 25  ICSA                    1716 non-null   float64
 26  WGS1YR                  1716 non-null   float64
 27  WGS2YR                  1716 non-null   float64
 28  NFCI                    1716 non-null   float64
 29  WTREGEN                 1716 non-null   float64
 30  WGS5YR                  1716 non-null   float64
 31  WBAA                    1716 non-null   float64
 32  DPSACBW027SBOG          1716 non-null   float64
 33  WCOILWTICO              1716 non-null   float64
 34  WGS30YR                 1716 non-null   float64
 35  WRESBAL                 1716 non-null   float64
 36  WGS20YR                 1716 non-null   float64
 37  MORTGAGE15US            1716 non-null   float64
 38  WPRIME                  1716 non-null   float64
 39  CCSA                    1716 non-null   float64
 40  TOTCI                   1716 non-null   float64
 41  RoR_Perc                1716 non-null   float64
 42  RoR_Intensity           1716 non-null   category
 43  Target_Rolling_shifted  1712 non-null   float64
dtypes: category(1), float64(43)
memory usage: 591.7 KB

In [20]:
cols_to_change = target_df.iloc[:, list(range(0, 41))].columns

# Loop through each column in the list
for col in cols_to_change:
    # Calculate percentage change
    pct_change = target_df[col].pct_change() * 100

    # Replace NaN values (from the first row) and infinity values
    pct_change.replace([np.inf, -np.inf], np.nan, inplace=True)  # Replace inf with NaN

    # Fill NaN values with 0 (from both first row or inf replacements)
    target_df[col + '_pct_change'] = pct_change.fillna(0)

In [21]:
final_df = target_df.copy()
final_df.drop(cols_to_change, axis=1)

,RoR_Perc,RoR_Intensity,Target_Rolling_shifted,Close_^DJI_pct_change,Close_^FCHI_pct_change,Close_^FTSE_pct_change,Close_^GDAXI_pct_change,Close_^GSPTSE_pct_change,Close_^HSI_pct_change,Close_^IXIC_pct_change,...,WBAA_pct_change,DPSACBW027SBOG_pct_change,WCOILWTICO_pct_change,WGS30YR_pct_change,WRESBAL_pct_change,WGS20YR_pct_change,MORTGAGE15US_pct_change,WPRIME_pct_change,CCSA_pct_change,TOTCI_pct_change
date,,,,,,,,,,,,,,,,,,,,,
1992-01-06,-0.321959,1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000
1992-01-13,-0.171062,1,0.0,-0.453111,2.053036,-0.124332,0.982122,1.974576,0.438818,3.299880,...,-0.658617,0.606685,-3.663004,-0.268456,-0.170401,0.000000,0.000000,0.000,-1.994135,-0.129018
1992-01-20,-0.596858,1,0.0,2.147159,2.280325,2.200707,3.992105,1.705432,4.267322,0.283341,...,0.662983,0.629639,2.172732,1.884253,-6.181224,0.000000,3.080873,0.000,-1.346499,0.082590
1992-01-27,-0.108322,1,0.0,-0.411798,0.182219,-0.196471,0.093164,-0.744042,0.979940,0.261551,...,0.548847,0.102548,-0.797448,1.056803,2.469709,0.000000,1.369863,0.000,2.032150,-0.299896
1992-02-03,0.181020,1,0.0,-0.200580,-0.658003,0.799246,-0.062247,-0.939785,2.577555,0.391303,...,0.436681,-0.222724,2.090032,1.176471,-17.226399,0.000000,1.719902,0.000,-1.872771,-0.013167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-21,-0.065551,1,0.0,-0.310267,-0.865951,0.307499,-0.241434,1.030197,-2.912872,0.201702,...,-0.357143,0.482246,-6.447351,0.000000,0.742890,-0.226757,4.066543,0.000,-1.853814,0.372629
2024-10-28,-0.178442,1,NaN,-1.267205,0.274805,-0.391919,0.361898,-0.637462,0.590369,0.146600,...,3.046595,-0.073514,1.101539,3.218391,0.631426,3.636364,1.420959,0.000,1.672963,-0.003503
2024-11-04,-0.217636,1,NaN,-1.398921,-2.451124,-1.223803,-1.964863,-1.260292,-0.154567,-2.085447,...,0.347826,0.098332,-4.050845,0.668151,0.210919,1.315789,4.903678,0.000,-0.583864,0.461169
2024-11-11,-0.124978,1,NaN,5.978110,0.748401,-0.720901,1.570672,2.198215,-0.683553,6.153908,...,-0.346620,0.000000,4.658611,-0.221239,1.148053,-0.216450,0.166945,0.000,0.000000,0.000000
2024-11-18,-0.676334,1,NaN,-1.224275,-1.549508,-0.664599,-0.950713,1.050447,-4.427883,-0.990268,...,0.000000,0.000000,0.000000,0.000000,-0.915391,0.000000,-0.166667,-2.625,0.000000,0.000000

In [22]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1716 entries, 1992-01-06 to 2024-11-18
Data columns (total 85 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Close_^DJI                 1716 non-null   float64
 1   Close_^FCHI                1716 non-null   float64
 2   Close_^FTSE                1716 non-null   float64
 3   Close_^GDAXI               1716 non-null   float64
 4   Close_^GSPTSE              1716 non-null   float64
 5   Close_^HSI                 1716 non-null   float64
 6   Close_^IXIC                1716 non-null   float64
 7   Close_^N225                1716 non-null   float64
 8   Volume_^DJI                1716 non-null   float64
 9   Volume_^FCHI               1716 non-null   float64
 10  Volume_^FTSE               1716 non-null   float64
 11  Volume_^GDAXI              1716 non-null   float64
 12  Volume_^GSPTSE             1716 non-null   float64
 13  Volume_^HSI                1716 non-null   float64
 14  Volume_^IXIC               1716 non-null   float64
 15  Volume_^N225               1716 non-null   float64
 16  SP500_Open                 1716 non-null   float64
 17  SP500_Close                1716 non-null   float64
 18  SP500_Volume               1716 non-null   float64
 19  SP500_Wk_Vol               1716 non-null   float64
 20  MORTGAGE30US               1716 non-null   float64
 21  FF                         1716 non-null   float64
 22  WGS10YR                    1716 non-null   float64
 23  WAAA                       1716 non-null   float64
 24  WTB3MS                     1716 non-null   float64
 25  ICSA                       1716 non-null   float64
 26  WGS1YR                     1716 non-null   float64
 27  WGS2YR                     1716 non-null   float64
 28  NFCI                       1716 non-null   float64
 29  WTREGEN                    1716 non-null   float64
 30  WGS5YR                     1716 non-null   float64
 31  WBAA                       1716 non-null   float64
 32  DPSACBW027SBOG             1716 non-null   float64
 33  WCOILWTICO                 1716 non-null   float64
 34  WGS30YR                    1716 non-null   float64
 35  WRESBAL                    1716 non-null   float64
 36  WGS20YR                    1716 non-null   float64
 37  MORTGAGE15US               1716 non-null   float64
 38  WPRIME                     1716 non-null   float64
 39  CCSA                       1716 non-null   float64
 40  TOTCI                      1716 non-null   float64
 41  RoR_Perc                   1716 non-null   float64
 42  RoR_Intensity              1716 non-null   category
 43  Target_Rolling_shifted     1712 non-null   float64
 44  Close_^DJI_pct_change      1716 non-null   float64
 45  Close_^FCHI_pct_change     1716 non-null   float64
 46  Close_^FTSE_pct_change     1716 non-null   float64
 47  Close_^GDAXI_pct_change    1716 non-null   float64
 48  Close_^GSPTSE_pct_change   1716 non-null   float64
 49  Close_^HSI_pct_change      1716 non-null   float64
 50  Close_^IXIC_pct_change     1716 non-null   float64
 51  Close_^N225_pct_change     1716 non-null   float64
 52  Volume_^DJI_pct_change     1716 non-null   float64
 53  Volume_^FCHI_pct_change    1716 non-null   float64
 54  Volume_^FTSE_pct_change    1716 non-null   float64
 55  Volume_^GDAXI_pct_change   1716 non-null   float64
 56  Volume_^GSPTSE_pct_change  1716 non-null   float64
 57  Volume_^HSI_pct_change     1716 non-null   float64
 58  Volume_^IXIC_pct_change    1716 non-null   float64
 59  Volume_^N225_pct_change    1716 non-null   float64
 60  SP500_Open_pct_change      1716 non-null   float64
 61  SP500_Close_pct_change     1716 non-null   float64
 62  SP500_Volume_pct_change    1716 non-null   float64
 63  SP500_Wk_Vol_pct_change    1716 non-null   float64
 64  MORTGAGE30US_pct_change    1716 non-null   float64
 65  FF_pct_change              1716 non-null   float64
 66  WGS10YR_pct_change         1716 non-null   float64
 67  WAAA_pct_change            1716 non-null   float64
 68  WTB3MS_pct_change          1716 non-null   float64
 69  ICSA_pct_change            1716 non-null   float64
 70  WGS1YR_pct_change          1716 non-null   float64
 71  WGS2YR_pct_change          1716 non-null   float64
 72  NFCI_pct_change            1716 non-null   float64
 73  WTREGEN_pct_change         1716 non-null   float64
 74  WGS5YR_pct_change          1716 non-null   float64
 75  WBAA_pct_change            1716 non-null   float64
 76  DPSACBW027SBOG_pct_change  1716 non-null   float64
 77  WCOILWTICO_pct_change      1716 non-null   float64
 78  WGS30YR_pct_change         1716 non-null   float64
 79  WRESBAL_pct_change         1716 non-null   float64
 80  WGS20YR_pct_change         1716 non-null   float64
 81  MORTGAGE15US_pct_change    1716 non-null   float64
 82  WPRIME_pct_change          1716 non-null   float64
 83  CCSA_pct_change            1716 non-null   float64
 84  TOTCI_pct_change           1716 non-null   float64
dtypes: category(1), float64(84)
memory usage: 1.1 MB

In [23]:
final_df[['Volume_^FCHI', 'Volume_^FCHI_pct_change']].head(10)

            Volume_^FCHI  Volume_^FCHI_pct_change
date
1992-01-06           0.0                      0.0
1992-01-13           0.0                      0.0
1992-01-20           0.0                      0.0
1992-01-27           0.0                      0.0
1992-02-03           0.0                      0.0
1992-02-10           0.0                      0.0
1992-02-17           0.0                      0.0
1992-02-24           0.0                      0.0
1992-03-02           0.0                      0.0
1992-03-09           0.0                      0.0

In [24]:
final_df = final_df.dropna()

In [25]:
final_df.to_csv('final_df.csv')

# 4 Data set oversampling and unsampling

## 4.1 Oversample

In [26]:
# Count values per unique value for 'RoR_Intensity'
ror_intensity_counts = final_df['RoR_Intensity'].value_counts()

ror_intensity_counts

RoR_Intensity
1    1540
0      86
2      86
Name: count, dtype: int64

In [27]:
#Oversample values for Outliers RoR_Intensity on which colum of Ror value is 0 and 2

from sklearn.utils import resample

# Separate majority and minority classes
ror_0 = final_df[final_df['RoR_Intensity'] == 0]
ror_2 = final_df[final_df['RoR_Intensity'] == 2]
ror_others = final_df[~final_df['RoR_Intensity'].isin([0,2])]

# Upsample minority class
ror_0_Oversampled = resample(ror_0,
                          replace=True,  # sample with replacement
                          n_samples=ror_others.shape[0], # to match majority class
                          random_state=123) # reproducible results

ror_2_Oversampled = resample(ror_2,
                          replace=True,  # sample with replacement
                          n_samples=ror_others.shape[0], # to match majority class
                          random_state=123) # reproducible results

# Combine majority class with upsampled minority class
Oversampled_df = pd.concat([ror_others, ror_0_Oversampled, ror_2_Oversampled])

# Display new class counts
Oversampled_df['RoR_Intensity'].value_counts()

RoR_Intensity
0    1540
1    1540
2    1540
Name: count, dtype: int64

In [28]:
Oversampled_df.to_csv('Oversampled_df.csv')

## 4.2 undersample

In [29]:
# Undersample

# Downsample the majority classes to match the minority class
n_samples = ror_0.shape[0]  # Use the size of the smallest class as the target size

ror_others_downsampled = resample(ror_others,
                               replace=False,  # sample without replacement
                               n_samples=n_samples,  # to match minority class
                               random_state=123) # reproducible results


# Combine minority class with downsampled majority class
downsampled_df = pd.concat([ror_0, ror_2, ror_others_downsampled])

# Display new class counts
downsampled_df['RoR_Intensity'].value_counts()

RoR_Intensity
0    86
1    86
2    86
Name: count, dtype: int64

In [30]:
downsampled_df.to_csv('downsampled_df.csv')